version: '3'
services:
  postgres:
    container_name: assistance-postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assistance

networks:
  postgres:
    driver: bridge