"""Add UserCourse table

Revision ID: 1ad43fd6c36d
Revises: 6abaa6bc4e1b
Create Date: 2023-11-03 23:38:06.193306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '1ad43fd6c36d'
down_revision = '6abaa6bc4e1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_course',
        sa.Column('user_email', sa.String(length=255), nullable=True),
        sa.Column('course_id', sa.UUID(), nullable=False),
        sa.Column('role', ENUM('admin', 'assistant', 'default', name='role_enum'), nullable=False, default='default'),
        sa.Column('active', sa.Boolean(), nullable=False, default=True),
        sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
        sa.PrimaryKeyConstraint('user_email', 'course_id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_course')
